version: '3.5'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/mydb"
    depends_on:
      - db
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres