pipeline {
    agent any

    stages {
        stage('Test app') {
            agent {
                docker {
                    image 'python:3.8-buster'
                }
            }
            steps {
                dir(path: 'DevOps/Lab1') {
                    sh 'pip install pipenv'
                    sh 'pipenv install --dev'
                    sh 'pipenv run pytest tests'
                }
            }
        }
        stage('Build image') {
            steps {
                dir(path: 'DevOps/Lab1') {
                    sh 'docker build -t web-app:latest .'
                }
            }
        }
        stage('Deploy service') {
            steps {
                dir(path: 'DevOps/Lab1') {
                    sh 'docker-compose up -d'
                }
            }
        }
        stage('Destroy service') {
            steps {
                dir(path: 'DevOps/Lab1') {
                    sh 'docker-compose down'
                }
            }
        }
        stage('Push image') {
            steps {
                dir(path: 'DevOps/Lab1') {
                    sh 'true'
                }
            }
        }
    }
}
